### ISSUE TITLE
windows build ?

### ISSUE THREAD

**Issue by jschueller** [conda-forge/suitesparse-feedstock#51]
is it possible in conda-forge ? seems defaults has windows builds of this

**Comment by minrk** [comment]
Looks like defaults uses https://github.com/jlblancoc/suitesparse-metis-for-windows/  I suppose we could do the same? It seems like a bit of a pain to maintain

**Comment by h-vetinari** [comment]
Seems that upstream has [performance issues](https://github.com/DrTimothyAldenDavis/SuiteSparse#about-the-blas-and-lapack-libraries) with openblas:
> ## About the BLAS and LAPACK libraries ##
> 
> *NOTE: Use of the Intel MKL BLAS is strongly recommended. A recent OpenBLAS can result in severe performance degradation. The reason for this is being investigated, and this may be resolved in the near future. Ignore the comments about OpenBLAS in the various user guides; those are out of date.*

Xref: DrTimothyAldenDavis/SuiteSparse#1 xianyi/OpenBLAS#2392

I wanted to tackle the windows build because it's affecting me in downstream packages, and investigated as well what [anaconda](https://github.com/AnacondaRecipes/suitesparse-feedstock/blob/master/recipe/meta.yaml) does. Seems they're still on 5.2.0.

**Comment by h-vetinari** [comment]
So, apparently, cvxopt [knows](https://github.com/cvxopt/cvxopt/blob/master/setup.py) how to build suitesparse on windows. This is what AnacondaRecipes does, and it worked for me in conda-forge/cvxopt-feedstock#42 as well. Eventually, it would be nice to replace that hack by having the windows build done in this feedstock, of course.

**Comment by h-vetinari** [comment]
Why close this issue? The oldest windows build is for 5.4.0, while master is on 5.10.1

**Comment by jschueller** [comment]
oh I thought it was fixed
